import type { EvalCase } from './cases.js'

export interface MinedPrompt {
  prompt: string
  triggeredSkills: string[]
  sessionFile: string
}

const textFromContent = (content: unknown): string | null => {
  if (typeof content === 'string') return content
  if (!Array.isArray(content)) return null
  const parts = content
    .filter((b: any) => b?.type === 'text' && typeof b.text === 'string')
    .map((b: any) => b.text)
  return parts.length > 0 ? parts.join('\n') : null
}

// 세션 로그의 type:"user" 이벤트가 전부 사람이 친 발화는 아니다. 하네스가 슬래시커맨드 확장,
// 로컬 커맨드 출력, 주입 컨텍스트를 같은 모양으로 끼워 넣는다. 이것들을 발화로 세면 두 배로
// 틀린다: 가짜 프롬프트가 케이스가 되고, 그 뒤의 Skill 호출이 가짜 쪽에 귀속돼 진짜 발화는
// "발동하지 않은 것"이 되어 negative 로 라벨링된다 (실측: 로컬 draft 에 실제로 그렇게 들어가 있었다).
const HARNESS_MARKERS = [
  /<command-name>/, /<command-message>/, /<command-args>/,
  /<local-command-stdout>/, /<local-command-caveat>/,
  /<system-reminder>/,
  /^Caveat: The messages below were generated by the user/,
  /^The user invoked `\//
]

export const isHarnessPrompt = (text: string, ev: { isMeta?: unknown }): boolean =>
  ev.isMeta === true || HARNESS_MARKERS.some(re => re.test(text.trim()))

export const extractPrompts = (jsonl: string, sessionFile: string): MinedPrompt[] => {
  const out: MinedPrompt[] = []
  let current: MinedPrompt | null = null

  for (const line of jsonl.split('\n')) {
    const t = line.trim()
    if (!t.startsWith('{')) continue

    let ev: any
    try { ev = JSON.parse(t) } catch { continue }

    if (ev.type === 'user') {
      const text = textFromContent(ev.message?.content)
      if (text === null) continue
      // 끼어든 이벤트에서 current 를 갈아치우지 않는 것이 핵심이다 — 갈아치우면 뒤따르는
      // Skill 호출의 귀속이 진짜 발화에서 도둑맞는다.
      if (isHarnessPrompt(text, ev)) continue
      current = { prompt: text, triggeredSkills: [], sessionFile }
      out.push(current)
      continue
    }

    if (ev.type === 'assistant' && current) {
      for (const block of ev.message?.content ?? []) {
        if (block?.type === 'tool_use' && block.name === 'Skill' && block.input?.skill) {
          current.triggeredSkills.push(block.input.skill)
        }
      }
    }
  }

  return out
}

const QUOTED = /"([^"]{2,60})"/g

// 폴백 추출에서 버리는 기능어 — description 상용구("Use when the user asks…")가 키워드로
// 새면 모든 프롬프트가 near-miss 후보가 된다.
const FALLBACK_STOPWORDS = new Set([
  'use', 'when', 'this', 'that', 'with', 'from', 'before', 'after', 'into', 'only',
  'must', 'should', 'the', 'and', 'for', 'are', 'was', 'has', 'have', 'not', 'any',
  'user', 'asks', 'wants', 'skill', 'skills'
])

// 인용부호 문구가 하나도 없는 description 의 폴백 (실측 2026-07-30: superpowers:brainstorming 은
// 인용 예시가 없어 키워드가 공집합 → 세션 1094개에서 near-miss 0건). draft 는 사람이 선별하는
// 후보 목록이라 정밀도보다 재현율이 우선이다 — 잡음은 선별 단계에서 버려진다. 한국어 어절은
// 조사가 붙은 채 잘리므로 3글자 이상 어절은 끝 한 글자를 뗀 형태도 함께 넣어 매칭 폭을 넓힌다.
export const fallbackKeywords = (description: string): string[] => {
  const out = new Set<string>()
  for (const m of description.matchAll(/[A-Za-z]{4,}/g)) {
    const word = m[0].toLowerCase()
    if (!FALLBACK_STOPWORDS.has(word)) out.add(word)
  }
  for (const m of description.matchAll(/[가-힣]{2,}/g)) {
    out.add(m[0])
    if (m[0].length >= 3) out.add(m[0].slice(0, -1))
  }
  return [...out]
}

export const keywordsFromDescription = (description: string): string[] => {
  const quoted: string[] = []
  for (const m of description.matchAll(QUOTED)) quoted.push(m[1])
  // 저자가 명시한 트리거 문구가 폴백 잡음보다 강한 신호다 — 있으면 그것만 쓴다.
  return quoted.length > 0 ? quoted : fallbackKeywords(description)
}

export const classify = (
  mined: MinedPrompt[],
  args: { skillId: string; keywords: string[] }
): { positives: MinedPrompt[]; nearMisses: MinedPrompt[] } => {
  const positives: MinedPrompt[] = []
  const nearMisses: MinedPrompt[] = []

  // 같은 문구를 여러 번 쳤고 한 번만 발동했다면, 그 프롬프트는 "발동하는 프롬프트"다.
  // 첫 등장으로 라벨을 고정하면 readdir 순서가 판정을 정해서, 실제로 발동하는 프롬프트가
  // negative 로 굳고 스킬이 정상 작동할 때마다 오발동으로 집계된다. Map 이 삽입 순서를
  // 지키므로 출력 순서는 그대로다.
  const byPrompt = new Map<string, MinedPrompt>()
  for (const m of mined) {
    const seen = byPrompt.get(m.prompt)
    if (!seen) { byPrompt.set(m.prompt, m); continue }
    if (!seen.triggeredSkills.includes(args.skillId) && m.triggeredSkills.includes(args.skillId)) {
      byPrompt.set(m.prompt, m)
    }
  }

  for (const m of byPrompt.values()) {
    if (m.triggeredSkills.includes(args.skillId)) {
      positives.push(m)
      continue
    }
    // 키워드가 걸렸는데 발동하지 않은 것 = 모델이 실제로 망설인 지점 (설계 §6-2)
    if (args.keywords.some(k => m.prompt.includes(k))) nearMisses.push(m)
  }

  return { positives, nearMisses }
}

// 원본 단위로 3:1 분할한다. 변형을 붙일 때 같은 원본이 두 split 에 흩어지면 안 된다 (설계 §6-3)
const splitFor = (i: number): 'train' | 'test' => (i % 4 === 3 ? 'test' : 'train')

export const toDraftCases = (args: {
  positives: MinedPrompt[]
  nearMisses: MinedPrompt[]
}): EvalCase[] => {
  const cases: EvalCase[] = []

  args.positives.forEach((m, i) => {
    cases.push({
      id: `p-${String(i + 1).padStart(3, '0')}`,
      prompt: m.prompt,
      expect: 'trigger',
      split: splitFor(i),
      source: `log:${m.sessionFile}`
    })
  })

  args.nearMisses.forEach((m, i) => {
    cases.push({
      id: `n-${String(i + 1).padStart(3, '0')}`,
      prompt: m.prompt,
      expect: 'no-trigger',
      split: splitFor(i),
      source: `log:near-miss:${m.sessionFile}`
    })
  })

  return cases
}

// 증강은 원본 1건당 CLI 를 한 번씩 부른다. 순차로 돌면 원본 10건에 수 분이 걸리고, 그동안
// 호출부가 "왜 안 끝나지" 하며 즉흥적인 대기 로직을 만들어 낸다. 동시에 돌리되 상한을 둔다 —
// CLI 프로세스를 무제한으로 띄우면 레이트 리밋에 걸려 오히려 느려진다.
// 결과는 입력 순서를 지킨다: draft 파일이 실행마다 다른 순서로 쓰이면 diff 가 무의미해진다.
// fn 이 던지면 전체가 거부된다 — 항목별 실패를 견뎌야 하는 호출부가 직접 잡는 것이 계약이다.
export const mapLimit = async <T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>
): Promise<R[]> => {
  const results = new Array<R>(items.length)
  let next = 0
  const worker = async (): Promise<void> => {
    while (true) {
      const i = next++
      if (i >= items.length) return
      results[i] = await fn(items[i], i)
    }
  }
  const workers = Math.max(1, Math.min(limit, items.length))
  await Promise.all(Array.from({ length: workers }, worker))
  return results
}

const DEFAULT_MINE_CONCURRENCY = 4

// 하나하나가 온전한 CLI 세션이라 넉넉히 잡을 값이 아니다. 환경에 맞춰 올릴 수는 있게 둔다.
export const mineConcurrency = (): number => {
  const raw = process.env.SKILL_EVAL_MINE_CONCURRENCY
  if (raw === undefined || !/^\d+$/.test(raw)) return DEFAULT_MINE_CONCURRENCY
  const n = Number(raw)
  return n > 0 ? n : DEFAULT_MINE_CONCURRENCY
}

export const buildAugmentPrompt = (prompt: string, n: number): string => `
아래 요청을 사용자가 다르게 말했을 법한 ${n}개의 표현으로 바꿔라.

## 원본
${prompt}

## 규칙
- 의도는 그대로 두고 표현만 바꾼다. 새로운 상황이나 새 시나리오를 만들지 마라.
- 존댓말/반말, 축약, 흔한 오타, 어순 변화 정도를 섞어라.
- 문자열 ${n}개가 든 JSON 배열만 출력하라. 다른 말은 붙이지 마라.
`.trim()

const ARRAY_BLOCK = /\[[\s\S]*?\]/

export const parseVariants = (raw: string): string[] => {
  const m = ARRAY_BLOCK.exec(raw)
  if (!m) return []
  try {
    const parsed = JSON.parse(m[0])
    if (!Array.isArray(parsed)) return []
    return parsed.filter((v): v is string => typeof v === 'string')
  } catch {
    return []
  }
}

// 변형은 원본의 split 과 expect 를 그대로 물려받는다.
// 같은 원본의 변형이 train 과 test 에 흩어지면 test 점수가 거짓으로 오른다 (설계 §6-3)
export const attachVariants = (original: EvalCase, variants: string[]): EvalCase[] =>
  variants.map((prompt, i) => ({
    id: `${original.id}-v${i + 1}`,
    prompt,
    expect: original.expect,
    split: original.split,
    source: `llm:variant-of:${original.id}`
  }))
